### PR TITLE
Dashboard structure setup and responsive landing page

### LINKED ISSUE #1: Child User Story #11
As a user, I want to use the website on several devices so that I am not limited to my desktop.

Acceptance criteria pending.

### LINKED ISSUE #2: Child User Story #12
As a user, I want to see the website when I visit its address so that I can view its contents.

Acceptance criteria pending.

### PR DESCRIPTION
**Pull request by comphonia**
Resolves #1 and resolves #2

### CODE REVIEW

**Review by calebpower — APPROVED** [review]

**Comment by calebpower** [comment]
@comphonia with this merge, `dev` is stale-- I didn't delete it just in case you had unstaged commits or something, but it might be good to sync it back or create a new `feature/` branch.

**Comment by comphonia** [comment]
@calebpower not important since its just spinning up a test server, but I think you can wait to approve it when we actually serve the static files to wherever.

**Comment by calebpower** [comment]
Haha oops-- I approved it as soon as I tested it after I saw the pull request go through. My bad.

**Comment by comphonia** [comment]
That's fine the issue #2 is still open

**Pull request merged**
